version: '3.3'

services:
  postgres:
    image: postgres:14
    container_name: prefect-postgres
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - "5432:5432"
  
  redis:
    image: redis:latest
    container_name: prefect-redis
    ports:
      - "6379:6379"
  
  prefect-server:
    build: .
    container_name: prefect-server
    command: bash -c "
      prefect config set PREFECT_API_DATABASE_CONNECTION_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}" &
      prefect server start
      "
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api
    depends_on:
      - postgres
      - redis
    ports:
      - "4200:4200"

  prefect-worker-1:
    build: .
    container_name: file-tracking-worker
    env_file: ".env"
    command: bash -c "
      prefect config set PREFECT_API_URL=http://prefect-server:4200/api &&
      sleep 25 &&
      python3 file-tracking-flow.py
      "
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_HOST:${POSTGRES_HOST}
      - REDIS_HOST:${REDIS_HOST}
    depends_on:
      - prefect-server
    volumes:
      - ./file-tracking-flow.py:/app/file-tracking-flow.py
      - ./src:/app/src

  prefect-worker-2:
    build: .
    container_name: file-loading-worker
    env_file: ".env"
    command: bash -c "
      prefect config set PREFECT_API_URL=http://prefect-server:4200/api &&
      sleep 25 &&
      python3 file-loading-flow.py
      "
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_HOST:${POSTGRES_HOST}
      - REDIS_HOST:${REDIS_HOST}
    depends_on:
      - prefect-server
    volumes:
      - ./file-loading-flow.py:/app/file-loading-flow.py
      - ./src:/app/src
volumes:
  postgres_data:
  .: